name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Create symbolic link
      run: ln -s "${TARGET}" "${HOME}/.vscode"
      env:
        TARGET: ${{ github.workspace }}/${{ github.action_path }}
    - name: Setup repository
      run: |
        echo "deb [arch=amd64] "${MIRROR}" stable main" | sudo tee "${SOURCE}"
        curl -fsSL "${SIGNER}" | sudo apt-key add -
        sudo apt-get update
      env:
        MIRROR: http://packages.microsoft.com/repos/vscode
        SIGNER: https://packages.microsoft.com/keys/microsoft.asc
        SOURCE: /etc/apt/sources.list.d/vscode.list
    - name: Install package
      run: sudo apt-get --assume-yes --no-install-recommends install code
    - name: Install extensions
      run: make init
    - name: Create artifact
      run: make bundle
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: vscode
        path: bundle.tgz